### ISSUE TITLE
Testing pace-util integration in fv3net 

### ISSUE THREAD

**Issue by brianhenn** [ai2cm/pace#184]
We discussed as a group that it's challenging to test the integration of PyPI packages we've created (eg `pace-util`) within `fv3net`. This documents how I am testing `pace-util` in `fv3net` before making a release, to try to avoid unexpected failures that would force another release (which is what happened when I made a PR and only ran the tests within the `pace` repo, because it's hard to anticipate the `fv3net` integration). 

`git grep` indicates `pace-util` is used in the following places:
- prognostic_c48_run (zarr monitor for prognostic run and for emulation via emulation package; also for nudging and prescribing)
- fv3fit (halos for CNNs)

To test the prognostic run image, I locally hacked its Dockerfile to install `pace-util` from source repo within fv3net (set to the dev branch) instead from PyPI, and built the image. Unfortunately I think this was needed because `pace-util` can't be pip installed from a git url, as it's part of the larger `pace` monorepo. See instructions [here](https://github.com/ai2cm/fv3net/blob/603b96f6059642dc464b12f371959117ebca6acd/docker/prognostic_run/Dockerfile#L96). Then I ran the prognostic run tests in the container. 

To test the `fv3fit` integration, I did a similar thing for the `fv3net` environment (which is where `fv3fit` runs in the `fv3net` container), and ran the `fv3fit` tests locally. Finally, I built images for the e2e test (`fv3net`, `prognostic_run`, `artifacts`, `post_process_run`) under a local commit and triggered the e2e test locally. 

I think collectively that covers our test exposure to `pace-util`.  We *could* replicate the above as an optional workflow in CI but it's probably not worth it, since we only want to do this when making new releases of pace-util, which probably isn't that often. 

But the above steps are time-consuming. At the very least, we should not add additional exposure to `pace-util` outside of the prognostic run image and fv3fit package (where it's already used) unless there's a good reason, as that would imply more integration testing needed.

**Comment by nbren12** [comment]
@brianhenn 
> Unfortunately I think this was needed because pace-util can't be pip installed from a git url, as it's part of the larger pace monorepo.

pip should support this.  [See these docs](https://pip.pypa.io/en/stable/topics/vcs-support/#url-fragments). Did you try syntax like this:
```
pip install -e "vcs+protocol://repo_url/#egg=pkg&subdirectory=pkg_dir"
```

**Comment by FlorianDeconinck** [comment]
Project ending.
